apps/media_stats_web/lib/media_stats_web/router.ex
defmodule MediaStatsWeb.Router do
  use MediaStatsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MediaStatsWeb.Plug.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MediaStatsWeb do
    pipe_through :browser

    get "/", PageController, :index

    # Session
    get    "/login", SessionController, :login
    post   "/login", SessionController, :login
    delete "/logout", SessionController, :logout

    #User
    get  "/sign-up", UserController, :sign_up
    post "/sign-up", UserController, :sign_up
  end

  scope "/dashboard", MediaStatsWeb do
    pipe_through [:browser, :authenticate_user]

    get "/", DashboardController, :index
    get "/pusher", DashboardController, :pusher
  end

  scope "/applications", MediaStatsWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/", ApplicationController, only: [:new, :create, :edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MediaStatsWeb do
  #   pipe_through :api
  # end
end

apps/media_stats_web/lib/media_stats_web/controllers/application_controller.ex
defmodule MediaStatsWeb.ApplicationController do
  use MediaStatsWeb, :controller

  alias MediaStats.Accounts.Application
  alias MediaStats.Accounts

  def create(conn, %{"application" => application_params}, current_user) do
    case MediaStats.Accounts.create_application(current_user, add_app_key(application_params)) do
      {:ok, _application} ->
        conn
        |> redirect(to: Routes.dashboard_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "create.html", changeset: changeset)
    end
  end

  def new(conn, _params, _current_user) do
    changeset = Application.registration_changeset(%Application{})
    render(conn, "create.html", changeset: changeset)
  end

  def update(conn, %{"id" => id, "application" => application_params}, current_user) do
    application = Accounts.get_user_application!(current_user, id)

    case MediaStats.Accounts.update_application(application, application_params) do
      {:ok, _application} ->
        conn
        |> redirect(to: Routes.dashboard_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}, current_user) do
    application = Accounts.get_user_application!(current_user, id)
    changeset = Application.changeset(application)
    render(conn, "edit.html", application: application, changeset: changeset)
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  defp add_app_key(application_params) do
    credentials = Map.put_new(application_params["credential"], "app_key", Ecto.UUID.generate())
    Map.update!(application_params, "credential", fn _ -> credentials end)
  end
end

apps/media_stats_web/lib/media_stats_web/controllers/dashboard_controller.ex
defmodule MediaStatsWeb.DashboardController do
  use MediaStatsWeb, :controller

  def index(conn, _params, current_user) do
    applications = MediaStats.Accounts.list_user_applications(current_user)
    render(conn, "index.html", applications: applications)
  end

  def pusher(conn, _params, _current_user) do
    render(conn, "pusher.html")
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end
end

apps/media_stats_web/lib/media_stats_web/controllers/page_controller.ex
defmodule MediaStatsWeb.PageController do
  use MediaStatsWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/media_stats_web/lib/media_stats_web/controllers/session_controller.ex
defmodule MediaStatsWeb.SessionController do
  use MediaStatsWeb, :controller

  def login(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    case MediaStatsWeb.Auth.login_by_email_and_pass(conn, email, pass) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.dashboard_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid user or password")
        |> render("login.html")
    end
  end

  def login(conn, _params) do
    render(conn, "login.html")
  end

  def logout(conn, _params) do
    conn
    |> MediaStatsWeb.Auth.logout()
    |> put_flash(:info, "See you soon!")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

apps/media_stats_web/lib/media_stats_web/controllers/user_controller.ex
defmodule MediaStatsWeb.UserController do
  use MediaStatsWeb, :controller
  alias MediaStats.Accounts.User

  def sign_up(conn, %{"user" => user_params}) do
    case MediaStats.Accounts.create_registered_user(user_params) do
      {:ok, user} ->
        conn
        |> MediaStatsWeb.Auth.login(user)
        |> put_flash(:info, "A new user has been created!")
        |> redirect(to: Routes.dashboard_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "sign_up.html", changeset: changeset)
    end
  end

  def sign_up(conn, _params) do
    changeset = User.registration_changeset(%User{}, %{})
    render(conn, "sign_up.html", changeset: changeset)
  end
end

apps/media_stats_web/lib/media_stats_web/views/application_view.ex
defmodule MediaStatsWeb.ApplicationView do
  use MediaStatsWeb, :view
end

apps/media_stats_web/lib/media_stats_web/views/dashboard_view.ex
defmodule MediaStatsWeb.DashboardView do
  use MediaStatsWeb, :view
end

apps/media_stats_web/lib/media_stats_web/views/error_view.ex
defmodule MediaStatsWeb.ErrorView do
  use MediaStatsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/media_stats_web/lib/media_stats_web/views/layout_view.ex
defmodule MediaStatsWeb.LayoutView do
  use MediaStatsWeb, :view
end

apps/media_stats_web/lib/media_stats_web/views/page_view.ex
defmodule MediaStatsWeb.PageView do
  use MediaStatsWeb, :view
end

apps/media_stats_web/lib/media_stats_web/views/session_view.ex
defmodule MediaStatsWeb.SessionView do
  use MediaStatsWeb, :view
end

apps/media_stats_web/lib/media_stats_web/views/user_view.ex
defmodule MediaStatsWeb.UserView do
  use MediaStatsWeb, :view

  alias MediaStats.Accounts.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end

  def render("user.json", %{user: user}) do
    %{
      id: user.id,
      username: user.username,
    }
  end
end

apps/media_stats_web/lib/media_stats_web/templates/application/create.html.eex
<div class="login-box px-3 py-3 pt-md-5 pb-md-4 mx-auto">
<h1>Create your new application</h1>

<%= if @changeset.action do %>
    <div class="alert alert-danger"><p>Oops, somethings went wrong! Please check errors below</p></div>
<% end %>

<%= form_for @changeset, Routes.application_path(@conn, :create), fn f -> %>
    <div class="form-group">
        <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
        <%= error_tag f, :name %>
    </div>

    <%= inputs_for f, :credential, fn cf -> %>
        <div class="form-group">
            <%= text_input cf, :allowed_hosts, placeholder: "Allowed hosts", class: "form-control" %>
            <%= error_tag cf, :allowed_hosts %>
        </div>
    <% end %>

    <%= link "Cancel", to: Routes.dashboard_path(@conn, :index), class: "btn btn-secondary"%>
    <%= submit "Create application", class: "btn btn-success" %>
<% end %>
</div>

apps/media_stats_web/lib/media_stats_web/templates/application/edit.html.eex
<div class="login-box px-3 py-3 pt-md-5 pb-md-4 mx-auto">
<h1>Edit your new application</h1>

<%= if @changeset.action do %>
    <div class="alert alert-danger"><p>Oops, somethings went wrong! Please check errors below</p></div>
<% end %>

<%= form_for @changeset, Routes.application_path(@conn, :update, @application), fn f -> %>
    <div class="form-group">
        <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
        <%= error_tag f, :name %>
    </div>

    <%= inputs_for f, :credential, fn cf -> %>
        <div class="form-group">
            <%= text_input cf, :allowed_hosts, placeholder: "Allowed hosts", class: "form-control" %>
            <%= error_tag cf, :allowed_hosts %>
        </div>

        <div class="form-group">
            <%= text_input cf, :app_key, placeholder: "App key", class: "form-control", readonly: true, disabled: true %>
            <%= error_tag cf, :app_key %>
        </div>
    <% end %>

    <%= link "Cancel", to: Routes.dashboard_path(@conn, :index), class: "btn btn-secondary"%>
    <%= submit "Update application", class: "btn btn-primary" %>
<% end %>
</div>

apps/media_stats_web/lib/media_stats_web/templates/dashboard/index.html.eex
<div class="col-md-12 d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-5 pb-2 mb-3 border-bottom">
    <h1 class="h2">My dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <%= link "New application", to: Routes.application_path(@conn, :new), class: "btn btn-sm btn-outline-secondary" %>
    </div>
</div>


<%= for application <- @applications do %>
<div class="col-md-12 pt-5 pb-2 mb-3">
    <h5>
      <%= link application.name, to: Routes.application_path(@conn, :edit, application.id)%>
    </h5>

    <div class="row" style="min-height: 250px">
        <div class="col-md-4 rt-active-users">
            <div data-rt-active-users="<%= application.credential.app_key %>" class="rt-active-users-counter"></div>
        </div>
        <div class="col-md-8" data-app-id="<%= application.credential.app_key %>">
            <ul class="list-group"></ul>
        </div>
    </div>
</div>
<% end %>

apps/media_stats_web/lib/media_stats_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Media stats</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">

          <%= if @current_user do %>
            <%= link "Media Stats", to: Routes.dashboard_path(@conn, :index), class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
          <% else %>
            <%= link "Media Stats", to: Routes.page_path(@conn, :index), class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
          <% end %>

          <ul class="nav justify-content-end">
          <%= if @current_user do %>

            <li class="nav-item text-nowrap">
              <%= link "Sign out", to: Routes.session_path(@conn, :logout), method: "delete", class: "nav-link" %>
            </li>

          <% else %>

            <li class="nav-item">
              <%= link "Register", to: Routes.user_path(@conn, :sign_up), class: "nav-link" %>
            </li>
            <li class="nav-item">
               <%= link "Login", to: Routes.session_path(@conn, :login), class: "nav-link" %>
            </li>
          <% end %>
          </ul>
        </nav>


    <div class="container-fluid">
        <div class="row px-5">
            <%= render @view_module, @view_template, assigns %>
        </div>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/media_stats_web/lib/media_stats_web/templates/session/login.html.eex
<div class="login-box px-3 py-3 pt-md-5 pb-md-4 mx-auto">
    <h3>Media stats login</h3>
    <%= form_for @conn, Routes.session_path(@conn, :login), [as: :session], fn f -> %>
        <div class="form-group">
            <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
            <%= error_tag f, :email %>
        </div>
        <div class="form-group">
            <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
            <%= error_tag f, :password %>
        </div>

        <%= submit "Login", class: "btn btn-primary" %>
    <% end %>
</div>

apps/media_stats_web/lib/media_stats_web/templates/user/sign_up.html.eex
<div class="login-box px-3 py-3 pt-md-5 pb-md-4 mx-auto">
    <h2>Welcome to media stats</h2>
    <%= form_for @changeset, Routes.user_path(@conn, :sign_up), fn f -> %>
        <div class="form-group">
            <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
            <%= error_tag f, :name %>
        </div>

        <%= inputs_for f, :credential, fn cf -> %>
            <div class="form-group">
                <%= text_input cf, :email, placeholder: "Email", class: "form-control" %>
                <%= error_tag cf, :email %>
            </div>
            <div class="form-group">
                <%= password_input cf, :password, placeholder: "Password", class: "form-control" %>
                <%= error_tag cf, :password %>
            </div>
        <% end %>
        <%= submit "Create user", class: "btn btn-primary" %>
    <% end %>
</div>